### ISSUE TITLE
JS dependencies diagram

### ISSUE THREAD

**Issue by thipages** [WebReflection/heresy#12]
Found interesting to share this project diagram (coming from IntelliJ IDE 2019.2.3) and see at one glance the "widget" architecture

![image](https://user-images.githubusercontent.com/130309/67849127-46571b00-fb06-11e9-8d45-7a252254a5c8.png)

**Comment by thipages** [comment]
By the way, withAccessor is rather useful, will it integrate core heresy?

**Comment by WebReflection** [comment]
`withAccessor` is a bit sketchy to be in core as is, but I'm working on `reactiveAttributes` which provides the same functionality with a better integration with the `init` callback.

**example**
```js
define('Span<span>', {
  reactiveAttributes: ['content'],
  oncontent({detail}) {
    this.textContent = detail;
  }
});

render(document.body, () => html`
  <p>This is <Span content=${'span content'} />?</p>
`);
```

The behavior is simple: `reactiveAttributes` is a list of attributes that can be used to get or set pretty much anything, and it automatically triggers an associated event, if any, once the set value is new, or it differs from the one previously set.

It's based on _WeakMap_, like it was for `withAccessor`, and it grants to trigger after the `init`.

Thoughts ? The branch is already up and running, thanks for feedback.

**Comment by WebReflection** [comment]
P.S. any other name different from `reactiveAttributes` would be considered, as I wouldn't know how to properly explain these kind of attributes

**Comment by thipages** [comment]
I see three modes of  html attribute values with litterals
- fixed (embed in litterals)
- static (initialized outside the element but never changing)
- dynamic (changing over time)

Other names:  dynamicAttributes, dynAttributes, reactAttributes ;-) , onAttributes

Can not test reactiveAttributes feature right now, will  later this week. I like it already anyway.

**Comment by WebReflection** [comment]
Thing is, these attributes are actually not really attributes, as these don't even show up in the node, cause these can have any value "attached" ... still thinking a better name, and ghostAttributes in Halloween seems appropriate too 😂

**Comment by WebReflection** [comment]
Or accessorAttributes 🤔

**Comment by thipages** [comment]
Yep. like the ghost one. 
Why not customAttributes....

**Comment by WebReflection** [comment]
Or maybe dataAttributes, hopefully not confusing with data-* ones

**Comment by thipages** [comment]
Stick to onAttributes

**Comment by WebReflection** [comment]
All events starts with `on` though, so maybe not 🤔

**Comment by thipages** [comment]
Oops. Lets reverse : attributesOn

**Comment by WebReflection** [comment]
I think I'm moving away from _attributes_ as a whole, 'cause these are never reflected on the actual DOM, so that simply naming these `accessors` would do a better job.

Thoughts?

**Comment by WebReflection** [comment]
just FYI, my current resolution for the name is `mappedAttributes`, as these are effectively mapped through a WeakMap, but represented in the markup as attributes.

I think this is the least confusing name for such kind of attributes, and I prefer it over `reactiveAttributes` and friends.

**Comment by thipages** [comment]
I use now mappedAttributes, thank you
also Todo app may loose a dependency

**Comment by WebReflection** [comment]
FYI, I've made few changes to always trigger events, or shallow identities won't ever trigger anything (i.e. with same list of items).

The heresy-todo helped finishing the shape of this feature, and it's been updated, so it'd be great to see the new dep graph with latest version, thanks.

**Comment by thipages** [comment]
![image](https://user-images.githubusercontent.com/130309/68083977-c267a080-fe2f-11e9-87d1-29bf6b1cbebe.png)

**Comment by WebReflection** [comment]
it looks better, doesn't it? thanks for the screenshot

**Comment by thipages** [comment]
It looks rather good!
