### ISSUE TITLE
Simplifying the attribute dot notation

### ISSUE THREAD

**Issue by thipages** [WebReflection/heresy#20]
Hi,
in order to have homogeneous attributes naming (without dots), is it possible to add a rule saying that mappedAttributes behave as former dotted attributes, others as DOM attributes?

**Comment by WebReflection** [comment]
those are two documented different kind of behavior, and you shouldn't use both style, just the standard way, and used mappedAttributes only for special cases.

**Comment by thipages** [comment]
these are lighterhtml behaviours, heresy may behave a bit different.
Anyway need to get real use case first.

**Comment by WebReflection** [comment]
lighterhtml needs better documentation for this, but the feature was designed to satisty heresy use case.

You don't need to use both cases, and `mappedAttributes` and `observedAttributes` are two different things, and it won't change 'cause these are mant to be two different things.

**Comment by thipages** [comment]
Thank you
