### ISSUE TITLE
High Order Component

### ISSUE THREAD

**Issue by alexey13** [WebReflection/heresy#24]
Good day Andrea!
Its working but is it valid for object litterals patten?

```
const Child = {
	extend: 'div',
	render() {
		this.html`
		<div>Child</div>`
	}
}

function HighOrderComponent(Component) {
	return {
		extend: 'div',
		includes: {Component},
		render() {
			this.html`
			<div>
				Parent
				<Component />
			</div>`
		}
	}
}

function home() {
	const Component = Object.assign({}, Child);
	const Page = HighOrderComponent(Component)
	define('Page', Page);
	render(document.body, html`<Page />`)
}

home()
```

**Comment by alexey13** [comment]
Is it possible to pass component into another component as mappedAttribute and render it. For example we have page layout and content of pages is different but layout is same. So we want to render changes in content only. If i use above strategy i will get rerender of whole page

**Comment by WebReflection** [comment]
if you extend a `div` you don't need to define the `<div>` in the HTML, as the component **is** already a div, so you'd have a redundant div wrapper.

example:
```js
const Child = {
	extend: 'div',
	render() {
		this.html`
		Child`
	}
}
```

> If i use above strategy i will get rerender of whole page

that's not accurate, as only new components within the page would be rendered.

> Is it possible to pass component into another component as mappedAttribute and render it?

This library is declarative, if you inject content differently, you are basically not using the declarative approach, so while it's technically possible, it makes little sense with this library to do so.

Do you have a practical example maybe I can suggest how to improve?

P.S. closing as this is not really a bug.

**Comment by alexey13** [comment]
Thanks for answer! Component that inited in promise not render. What do you recommend to use for  async components?

```
this.html`
<div class="container">
	${getData().then(data => html`<Component .data =${data} />`)}
</div>`;
```

**Comment by WebReflection** [comment]
Heresy goal is to provide a JSX-less syntax, and differently from hyperHTML, lighterhtml doesn't support Promise in holes.

How would you do that in JSX?

**Comment by alexey13** [comment]
I dont React:) Dont know Andrea, i am lighterhtml user:)))
Trying to migrate to heresy:))

**Comment by WebReflection** [comment]
Then render on promise resolved, moving `this.html` declaration within, your component will be just fine

**Comment by alexey13** [comment]
Yes its rendered if I use this.html in then, but only child component data get rendered and another data in parent component get erased

**Comment by alexey13** [comment]
Made fetch data inside of the component. As i see its recomended way. I hope that i not annoying you with my questions?

**Comment by WebReflection** [comment]
this is what I meant

```js
getData().then(data => {
  this.html`
  <div class="container">
    <Component .data =${data} />
  </div>`;
});
```

P.S. heresy components are already wrappers, you don't need extra divs ... the pattern is different from lighterhtml, you have an element already, you don't create the element.

**Comment by alexey13** [comment]
Heresy is really awesome. New level for me. Worth to migrate to it. The more I use Heresy the more I love it. Heresy help tp build a very structured app.

**Comment by alexey13** [comment]
Is it the right way to use augmentor? Its very cool we can use mapped attributes and on events or we can use hooks. I think that using hooks for external data and mapped for inner data

```
export const List = {
	extends: 'div',
	includes: {Item},
	onclick(e) {
		const page = e.target.dataset.page;
		this.setPage(page)
	},
	render({useEffect, useState}) {
		const [items, setItems] = useState([]);
		const [page, setPage] = useState(1);
		this.setPage = setPage;

		useEffect(() => {
			getData()
			.then(data => setItems(data));
		}, [])

		this.html`${items.map(c => html`<Item onclick=${this} .item=${c} />`)}`
	}
}
```

**Comment by WebReflection** [comment]
There's no right or wrong, if you're happy with the pattern and it solves your needs then go for it

**Comment by alexey13** [comment]
Same using mappedAttributes and Heresy events. Cool.
```
export const List = {
	extends: 'div',
	includes: {Item},
	mappedAttributes: ['items'],
	oninit() {
		this.items = [];
		getData()
			.then(data => this.items = data);
	},
	onitems() {
		this.render()
	},
	onclick(e) {
		const page = e.target.dataset.page;
		this.page = page
		this.render()
	},
	render() {
		const {items} = this;
		this.html`${items.map(c => html`<Item onclick=${this} .item=${c} />`)}`
	}
}
```

**Comment by WebReflection** [comment]
Any reason for your list to extend DIV instead of UL ? anyway, that's another way, probably the way I'd use. In any case, if you like hooks in render, you can still call `this.render()` whenever needed, as hooks are always available as first argument anyway.

**Comment by alexey13** [comment]
`Any reason for your list to extend DIV instead of UL ?`
For UL element i will get list style CSS properties. And childs of that list not li elements. This list not a "classic" UL list style.
Yes, i think too that the second one is better. Do not like so much code in the render function that related to data. But hooks are awesome for external data i think, from global storage for example

**Comment by alexey13** [comment]
Good day, Andrea! I try to make a Modal component. But looks like i cant pass component in another component right?
Tried
```
<Modal .data=${{title: '', show}}>
  <Component .items=${{all, checked}} />
</Modal>
```
But offcourse its not working if Modal have child elements. Tried to pass component as mappedAttribute but not working.
```
<Modal .data=${{title: '', show, component: `<Component .items=${{all, checked}} />`}} />
```
So what you recommend to do in such ways? Big thanks!
