### ISSUE TITLE
In Safari render() being run before the constructor() resulting in this.refs failing with undefined value as useRef never called

### ISSUE THREAD

**Issue by AhnafCodes** [WebReflection/heresy#25]
https://codepen.io/ahnafcodes/pen/PooyGdK

Steps: 
1. please open the above [codepen](https://codepen.io/ahnafcodes/pen/PooyGdK) in Safari browser and in chrome. It works in chrome and fails to render in safari. 
2. Please open debugger in chrome and safari
3. Reload each browser to see the difference. 
![safariRefsFailing](https://user-images.githubusercontent.com/7367600/73397758-cf1e5800-42a9-11ea-91df-ee1be71e825b.png)

Behavior: 
I have set debugger in "constructor" and "render" as you can see in codepen, oddly in the safari browser the render() runs before constructor().              

It might be a custom component api issue in Safari, Unfortunately Safari is the default browser for Ipad users.

**Comment by AhnafCodes** [comment]
Does this issue stem from this 
https://github.com/wikipathways/pvjs/issues/408

**Comment by AhnafCodes** [comment]
I don't want to do this: 
```if(isSafari && !this.refs) { this.constructor(); } // looks hacky and is ugly```

**Comment by WebReflection** [comment]
Will have a look once I get a chance to be in front of a PC (hopefully soon)

**Comment by WebReflection** [comment]
I think the issue is tat you are using `constructor` which is forbidden in Safari ... use `oninit` event/method to define **once** anything you need, including refs.
