### ISSUE TITLE
Question: Analog for `props.children`?

### ISSUE THREAD

**Issue by ryansolid** [WebReflection/heresy#26]
I know you've been talking about how you can use Custom Elements without the Shadow DOM and refer to it about styling, but I think I'm still missing something. The very first sort of example, I think of when I think of custom elements is container elements. Especially with composition so that I can build components in the style of my project and not have to worry about DOM layouts over and over again. Custom list boxes, tooltips, modals, sticky headers, nav bars etc... How does that work with heresy? Like:

```js
html`<MyModal title="My Header" confirmButton="Continue">
  <p>My first paragraph</p>
  <p>My second paragraph</p>
</MyModal>`
```
Where `Modal` also has a render function that draws the header with the title, and the button with the supplied text and inserts the body as it sees fit. 

How does this work? Is the answer to just use my own prop like children?
```js
html`<MyModal
  title="My Header"
  confirmButton="Continue"
  children=${html`
    <p>My first paragraph</p>
    <p>My second paragraph</p>
  `}
/>`
```

**Comment by WebReflection** [comment]
Why not just this?

```js
html`<MyModal title="My Header" confirmButton="Continue">
  ${html`
    <p>My first paragraph</p>
    <p>My second paragraph</p>
  `}
</MyModal>`
```

Also if you want to reach children either use `this.children` right away, or [the ref() utility](https://github.com/WebReflection/heresy#local-components-in-a-nutshell).

**Comment by ryansolid** [comment]
I guess I didn't really show what I meant properly only showing it from the outside since I was preoccupied with passing it in. Pretend this is the modal component, would `this.children` work as wouldn't the render content also be the children?

```js
const Modal = {
  extends: 'div',
  render() {
    this.html`
      <div class="modal-container">
        <h1>${this.props.title}</h1>
        ${this.children} 
        <button>Ok</button>
      </div>
    <div class="modal-backdrop" />
    `;
  }
};
```
Maybe this just works and this issue is for nothing. From my understanding of the library I was unclear how this would work. The `this.children` above is what I mean by `props.children` in the React context. The ability to just insert the children passed from the parent anywhere within your rendering.

**Comment by WebReflection** [comment]
So, `this.children` is the DOM meaning, notthing magic, hence you cannot pass `this.children` like that, you can reach `this.children` *only* after a render, but that's not what you are after.

*However*, if it's the content that you are after, and that won't change, you can always do this:

```js
const Modal = {
  extends: 'div',
  oninit() {
    this.originalContent = [].slice.call(this.children);
  },
  render() {
    this.html`
      <div class="modal-container">
        <h1>${this.props.title}</h1>
        ${this.originalContent} 
        <button>Ok</button>
      </div>
    <div class="modal-backdrop" />
    `;
  }
};
```

This would allow you to trap the original nodes once, and place these within the render, in a way similar to what slots do with Shadow DOM.

**Comment by ryansolid** [comment]
Right.. which takes us back to what I was trying to ask at the beginning. I guess I was wondering if there was any sort of conflict on re-render of the parent component. Since generally if data updates in a component you end up re-evaluating the children. Like if `MyModal` lived on `MyPage`and it essentially renders the children again. Like in this example:
```js
html`<MyModal title="${state.header}" confirmButton="Continue">
  ${html`
    <p>My first paragraph</p>
    <p>My second paragraph</p>
  `}
</MyModal>`
```
If header changed would that mess with things? I guess if the renderer keeps a reference to the rendered node when it it's the template literal again it would update that node where-ever it currently is placed and would not try to re-reconcile all the components children?

**Comment by WebReflection** [comment]
if your question is: is there re-conciliation in heresy? the answer is no, heresy is Custom Elements based, and Custom Elements don't have reconciliation.

The slot concept is the closest one, but you can't reconciliate slots with Custom Elements, you either declare content, or not, but also ... nobody should care about this, as re-renders are kinda invisible to users, and Custom Elements pseudo re-hydration is blazing fast, as in this case.

If this bug is about implementing re-conciliation, I think re-conciliation is not a Custom Elements matter, just something very specific to React, so if you search React elsewhere, I suggest to stick with React as you already know what you are looking for 😉

**Comment by ryansolid** [comment]
Yeah I realize from your response I am doing a terrible job. I'm just so used to talking in circles where React is the defacto language of the web, even though I don't use it much myself. I think I can ask this is a clearer way using Web Component language.

Does Heresy without the Shadow DOM provide a way to do dynamic slotting? Ie.. to say pass a couple items as children to the custom element, and render them in a certain position, and then when those children change (like you add something to the end) those also get slotted in the right place.

That was basically the whole question. I had seen you talk about using Web Components without the Shadow DOM and I was wondering if there is any difference here. I've written polyfills for the Shadow DOM myself in the past and it's always been a pain but necessary to do this very fundamental behavior to Web Components. The Shadow DOM handles this automatically for you without consideration and in my opinion more than styling is its reason for existence. I was just curious Heresy had some approach to address this very core need.

**Comment by WebReflection** [comment]
Thing is, you can grab nodes and put these in the template as interpolation, but you need to manually update these nodes a part, because these are not imported.

Heresy is basically a glorified declarative never name clashing technique to ship custom elements or simply nodes, but that's about it.

Re-hydration with custom elements is done natively, but re-conciliation is not something the template literal can do, as it wouldn't know where to find what, so nodes are replaced on the fly, if you just declare some content.

Maybe one day I'll provide a way to explicitly adopt known nodes via the template literal, but for the time being, non of my libraries do that, and I'm not sure if any library of this kind would.

**Comment by JDvorak** [comment]
Would passing children to a custom element really require reconciliation? It seems like it would just need to be pass the reference node and make sure to attach at the point specified by the parent. Is there a massive constraint or complexity that makes implementing this more difficult?

**Comment by Scott-MacD** [comment]
I know this is an older post, but I just wanted to post the solution we're currently using for this in case it's of use for anyone else, as we've struggled with this on multiple projects in the past as well.

Now that lighterHTML (and by extension, heresy) has property accessors directly on nodes, you can add child nodes in a more natural way closer to how React or custom element slots works, by creating an interpolated property as your last attribute on an element, something like the following example simplified `accordion` component.

```js
export default {
    name: "accordion",
    extends: "details",

    head: "",
    body: null,

    render() {
        this.html`
            <summary class="head">${this.head}</summary>
            <div class="body">${this.body}</div>
        `;
    }
}
```

This could then be used like the following:
```js
html`

<Accordion .head=${"Click to Toggle"} .body=${html.for(this, "some-id")`

    <h1>Any random HTML can go here</h1>

    <p>This HTML is completely independant to the Accordion component and the Accordion component doesn't care about what this content is.</p>

    <p>We can even add another <CustomComponent />, or even embed another</p>

    <Accordion .head=${"Child accordion"} .body=${html.for(this, "another-id")`
        I'm html within an accordion, within an accordion! <b>Inception!</b>
    `} />

`} />

`;
```

That child content is completely decoupled from the `<Accordion>` component, but can still be accessed from the Accordion via `this.body` if it needs to evaluate or transform it in any way. It gets a little less elegant if you have multiple "slots" with big blocks of HTML as children, but I hope this is useful to somebody else encountering the same issue.
