### ISSUE TITLE
Support for @ungap/custom-elements

### ISSUE THREAD

**Issue by CaptainJKoB** [WebReflection/heresy#40]
Hello,

To support built-in custom elements in Safari the [@ungap/custom-elements-builtin](https://github.com/ungap/custom-elements-builtin) needs to be included. But in it's repo it's stated that the package is deprecated in favor of [@ungap/custom-elements](https://github.com/ungap/custom-elements).

I'm testing on MacOS 10.15.3, Safari 13.0.5. and only the deprecated package is working properly.
The `onprops` listener is not firing.
Chrome, Firefox working as intended. Don't know about newer versions of Safari.

[Codepen sample](https://codepen.io/captainjkob/pen/oNzVMZm)

Is there any chance to support it? Thank you.

**Comment by WebReflection** [comment]
testing this https://webreflection.github.io/custom-elements/test/ (sorry, it was for myself on mobule)

**Comment by CaptainJKoB** [comment]
> testing this https://webreflection.github.io/custom-elements/test/ (sorry, it was for myself on mobule)

The polyfill seems to work nicely. 
The component inits, connects, renders normally.
But if I try to re-render, nothing happens.

**Comment by WebReflection** [comment]
this works ... hence it's not a polyfill issue, it's a *heresy* one ... will have a look whenever I find the time:
https://codepen.io/WebReflection/pen/xxEBQRJ?editors=0010

**Comment by WebReflection** [comment]
plot twist: it *was* a polyfill issue ... fixed 👋
